export const EnumPayment = [
    {
        description: "BCA Kartu Kredit Cicilan 0%",
        id: 2,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-041512-BCA.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 14,
                is_active: 1,
                issuer: "30000259",
                issuer_name: "3 Bulan",
                master_cicilan_id: "2",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 15,
                is_active: 1,
                issuer: "30000015",
                issuer_name: "6 Bulan",
                master_cicilan_id: "2",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 16,
                is_active: 1,
                issuer: "30000012",
                issuer_name: "12 Bulan",
                master_cicilan_id: "2",
                sequence: 2,
                price: 1854083,
            },
        ],
        name: "BCA",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-041512-BCA.png",
    },
    {
        description: "BNI Kartu Kredit Cicilan 0%",
        id: 3,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-041808-BNI.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 17,
                is_active: 1,
                issuer: "30000048",
                issuer_name: "3 Bulan",
                master_cicilan_id: "3",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 18,
                is_active: 1,
                issuer: "30000049",
                issuer_name: "6 Bulan",
                master_cicilan_id: "3",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 19,
                is_active: 1,
                issuer: "30000045",
                issuer_name: "12 Bulan",
                master_cicilan_id: "3",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 18,
                id: 20,
                is_active: 1,
                issuer: "30000046",
                issuer_name: "18 Bulan",
                master_cicilan_id: "3",
                sequence: 3,
                price: 1236055,
            },
            {
                due_month: 24,
                id: 21,
                is_active: 1,
                issuer: "30000047",
                issuer_name: "24 Bulan",
                master_cicilan_id: "3",
                sequence: 4,
                price: 927041,
            },
        ],
        name: "BNI",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-041808-BNI.png",
    },
    {
        description: "BRI Kartu Kredit Cicilan 0%",
        id: 4,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-042354-BRI.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 27,
                is_active: 1,
                issuer: "30000056",
                issuer_name: "3 Bulan",
                master_cicilan_id: "4",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 28,
                is_active: 1,
                issuer: "30000058",
                issuer_name: "6 Bulan",
                master_cicilan_id: "4",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 29,
                is_active: 1,
                issuer: "30000053",
                issuer_name: "12 Bulan",
                master_cicilan_id: "4",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 18,
                id: 30,
                is_active: 1,
                issuer: "30000054",
                issuer_name: "18 Bulan",
                master_cicilan_id: "4",
                sequence: 3,
                price: 1236055,
            },
            {
                due_month: 24,
                id: 31,
                is_active: 1,
                issuer: "30000055",
                issuer_name: "24 Bulan",
                master_cicilan_id: "4",
                sequence: 4,
                price: 927041,
            },
        ],
        name: "BRI",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-042354-BRI.png",
    },
    {
        description: "Bank Syariah Indonesia Kartu Kredit Cicilan 0%",
        id: 5,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-042803-bsi.jpg",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 140,
                is_active: 1,
                issuer: "30000382",
                issuer_name: "3 Bulan",
                master_cicilan_id: "5",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 141,
                is_active: 1,
                issuer: "30000383",
                issuer_name: "6 Bulan",
                master_cicilan_id: "5",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 142,
                is_active: 1,
                issuer: "30000384",
                issuer_name: "12 Bulan",
                master_cicilan_id: "5",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 24,
                id: 143,
                is_active: 1,
                issuer: "30000385",
                issuer_name: "24 Bulan",
                master_cicilan_id: "5",
                sequence: 3,
                price: 927041,
            },
        ],
        name: "BSI",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-042803-bsi.jpg",
    },
    {
        description: "CIMB Niaga Kartu Kredit Cicilan 0%",
        id: 6,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-043017-CIMB.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 6,
                id: 41,
                is_active: 1,
                issuer: "30000381",
                issuer_name: "6 Bulan",
                master_cicilan_id: "6",
                sequence: 0,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 42,
                is_active: 1,
                issuer: "30000378",
                issuer_name: "12 Bulan",
                master_cicilan_id: "6",
                sequence: 1,
                price: 1854083,
            },
        ],
        name: "CIMB Niaga",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-043017-CIMB.png",
    },
    {
        description: "DBS Kartu Kredit Cicilan 0%",
        id: 8,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2023-10-26-044952-logo-payment-bank-DBS-2023.jpg",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 98,
                is_active: 1,
                issuer: "30000022",
                issuer_name: "3 Bulan",
                master_cicilan_id: "8",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 99,
                is_active: 1,
                issuer: "30000023",
                issuer_name: "6 Bulan",
                master_cicilan_id: "8",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 100,
                is_active: 1,
                issuer: "30000021",
                issuer_name: "12 Bulan",
                master_cicilan_id: "8",
                sequence: 2,
                price: 1854083,
            },
        ],
        name: "DIGIBANK DBS",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2023-10-26-044952-logo-payment-bank-DBS-2023.jpg",
    },
    {
        description: "HSBC Kartu Kredit Cicilan 0%",
        id: 9,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-044828-HSBC.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 50,
                is_active: 1,
                issuer: "30000306",
                issuer_name: "3 Bulan",
                master_cicilan_id: "9",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 51,
                is_active: 1,
                issuer: "30000026",
                issuer_name: "6 Bulan",
                master_cicilan_id: "9",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 52,
                is_active: 1,
                issuer: "30000024",
                issuer_name: "12 Bulan",
                master_cicilan_id: "9",
                sequence: 2,
                price: 1854083,
            },
        ],
        name: "HSBC",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-044828-HSBC.png",
    },
    {
        description: "Mandiri Kartu Kredit Cicilan 0%",
        id: 10,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-045111-Mandiri.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 132,
                is_active: 1,
                issuer: "30000157",
                issuer_name: "3 Bulan",
                master_cicilan_id: "10",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 133,
                is_active: 1,
                issuer: "30000141",
                issuer_name: "6 Bulan",
                master_cicilan_id: "10",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 134,
                is_active: 1,
                issuer: "30000138",
                issuer_name: "12 Bulan",
                master_cicilan_id: "10",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 18,
                id: 135,
                is_active: 1,
                issuer: "30000139",
                issuer_name: "18 Bulan",
                master_cicilan_id: "10",
                sequence: 3,
                price: 1236055,
            },
            {
                due_month: 24,
                id: 136,
                is_active: 1,
                issuer: "30000140",
                issuer_name: "24 Bulan",
                master_cicilan_id: "10",
                sequence: 4,
                price: 927041,
            },
        ],
        name: "MANDIRI",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-045111-Mandiri.png",
    },
    {
        description: "Maybank Kartu Kredit Cicilan 0%",
        id: 11,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-045349-Maybank.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 57,
                is_active: 1,
                issuer: "30000350",
                issuer_name: "3 Bulan",
                master_cicilan_id: "11",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 58,
                is_active: 1,
                issuer: "30000352",
                issuer_name: "6 Bulan",
                master_cicilan_id: "11",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 59,
                is_active: 1,
                issuer: "30000351",
                issuer_name: "12 Bulan",
                master_cicilan_id: "11",
                sequence: 2,
                price: 1854083,
            },
        ],
        name: "Maybank",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-045349-Maybank.png",
    },
    {
        description: "Permata Kartu Kredit Cicilan 0%",
        id: 13,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2022-07-05-045949-Permata.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 125,
                is_active: 1,
                issuer: "30000313",
                issuer_name: "3 Bulan",
                master_cicilan_id: "13",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 126,
                is_active: 1,
                issuer: "30000029",
                issuer_name: "6 Bulan",
                master_cicilan_id: "13",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 127,
                is_active: 1,
                issuer: "30000027",
                issuer_name: "12 Bulan",
                master_cicilan_id: "13",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 18,
                id: 128,
                is_active: 1,
                issuer: "30000028",
                issuer_name: "18 Bulan",
                master_cicilan_id: "13",
                sequence: 3,
                price: 1236055,
            },
            {
                due_month: 24,
                id: 129,
                is_active: 1,
                issuer: "30000377",
                issuer_name: "24 Bulan",
                master_cicilan_id: "13",
                sequence: 4,
                price: 927041,
            },
        ],
        name: "Permata",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2022-07-05-045949-Permata.png",
    },
    {
        description: "UOB Kartu Kredit Cicilan 0%",
        id: 14,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2023-10-26-045523-logo-payment-bank-UOB-&-TMRW.jpg",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 117,
                is_active: 1,
                issuer: "30002577",
                issuer_name: "3 Bulan",
                master_cicilan_id: "14",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 118,
                is_active: 1,
                issuer: "30002578",
                issuer_name: "6 Bulan",
                master_cicilan_id: "14",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 119,
                is_active: 1,
                issuer: "30002579",
                issuer_name: "12 Bulan",
                master_cicilan_id: "14",
                sequence: 2,
                price: 1854083,
            },
        ],
        name: "UOB",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2023-10-26-045523-logo-payment-bank-UOB-&-TMRW.jpg",
    },
    {
        description: "Danamon Kartu Kredit Cicilan 0%",
        id: 15,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2024-02-21-061928-danamon-logo-payment-feb-rev.jpg",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 151,
                is_active: 1,
                issuer: "30000391",
                issuer_name: "3 Bulan",
                master_cicilan_id: "15",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 152,
                is_active: 1,
                issuer: "30000392",
                issuer_name: "6 Bulan",
                master_cicilan_id: "15",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 153,
                is_active: 1,
                issuer: "30000393",
                issuer_name: "12 Bulan",
                master_cicilan_id: "15",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 18,
                id: 154,
                is_active: 1,
                issuer: "30295797",
                issuer_name: "18 Bulan",
                master_cicilan_id: "15",
                sequence: 3,
                price: 1236055,
            },
            {
                due_month: 24,
                id: 155,
                is_active: 1,
                issuer: "30295798",
                issuer_name: "24 Bulan",
                master_cicilan_id: "15",
                sequence: 4,
                price: 927041,
            },
        ],
        name: "Danamon",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2024-02-21-061928-danamon-logo-payment-feb-rev.jpg",
    },
    {
        description: "Jenius BTPN Kartu Kredit Cicilan 0%",
        id: 16,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2023-01-17-101145-Logo_Payment_Checkout_Jenius.png",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 137,
                is_active: 1,
                issuer: "30149458",
                issuer_name: "3 Bulan",
                master_cicilan_id: "16",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 138,
                is_active: 1,
                issuer: "30149459",
                issuer_name: "6 Bulan",
                master_cicilan_id: "16",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 139,
                is_active: 1,
                issuer: "30149460",
                issuer_name: "12 Bulan",
                master_cicilan_id: "16",
                sequence: 2,
                price: 1854083,
            },
        ],
        name: "JENIUS",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2023-01-17-101145-Logo_Payment_Checkout_Jenius.png",
    },
    {
        description: "OCBC Kartu Kredit Cicilan 0%",
        id: 17,
        image_url:
            "https://pmp.eraspace.com/master-cicilan-files/2023-10-26-044921-ocbc-logo-payment.jpg",
        is_active: 1,
        issuer_cicilan: [
            {
                due_month: 3,
                id: 120,
                is_active: 1,
                issuer: "30000311",
                issuer_name: "3 Bulan",
                master_cicilan_id: "17",
                sequence: 0,
                price: 7416333,
            },
            {
                due_month: 6,
                id: 121,
                is_active: 1,
                issuer: "30000312",
                issuer_name: "6 Bulan",
                master_cicilan_id: "17",
                sequence: 1,
                price: 3708166,
            },
            {
                due_month: 12,
                id: 122,
                is_active: 1,
                issuer: "30000310",
                issuer_name: "12 Bulan",
                master_cicilan_id: "17",
                sequence: 2,
                price: 1854083,
            },
            {
                due_month: 18,
                id: 123,
                is_active: 1,
                issuer: "30002594",
                issuer_name: "18 Bulan",
                master_cicilan_id: "17",
                sequence: 3,
                price: 1236055,
            },
            {
                due_month: 24,
                id: 124,
                is_active: 1,
                issuer: "30002595",
                issuer_name: "24 Bulan",
                master_cicilan_id: "17",
                sequence: 4,
                price: 927041,
            },
        ],
        name: "OCBC",
        thumbnail_url:
            "https://pmp.eraspace.com/master-cicilan-files/thumbnail-2023-10-26-044921-ocbc-logo-payment.jpg",
    },
]
